### ISSUE TITLE
当前重构进度?

### ISSUE THREAD

**Issue by jk4235** [rashagu/dnd-kit-vue#1]
我准备重构的,发现已经有这个库了,所以想问一下目前进度到多少了?可以使用了嘛?

**Comment by rashagu** [comment]
能用。但是问题很多，用了很多computed导致sortable 性能不是很好

发自我的 iPhone

在 2023年1月12日，17:36，jk4235 ***@***.***> 写道：

﻿

我准备重构的,发现已经有这个库了,所以想问一下目前进度到多少了?可以使用了嘛?

**Comment by rashagu** [comment]
官方即将推出无关框架的版本[https://next.dndkit.com/overview](https://next.dndkit.com/overview)
